create table
  rules (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    name text,
    conditions jsonb,
    actions jsonb,
    user_id uuid references auth.users (id)
  );

alter table rules enable row level security;
