-- Create a type for the user roles
create type user_role as enum ('admin', 'analyst', 'viewer');

-- Create the workspaces table
create table
  workspaces (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    name text
  );

-- Create the workspace_users table to manage user roles in workspaces
create table
  workspace_users (
    id bigint generated by default as identity primary key,
    workspace_id bigint references workspaces (id),
    user_id uuid references auth.users (id),
    role user_role
  );

-- Alter the datasets table to be associated with a workspace instead of a user
alter table datasets add column workspace_id bigint references workspaces (id);
alter table datasets drop column user_id;
