-- Enable the pgvector extension
create extension if not exists vector;

-- Create the documents table to store the embeddings
create table
  documents (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    content text,
    embedding vector(1536),
    dataset_id bigint references datasets (id)
  );

-- Create a function to search for documents
create function match_documents (
  query_embedding vector(1536),
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    documents.id,
    documents.content,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;
